# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calibrationwidget.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_calibrationwidget(object):
    def setupUi(self, calibrationwidget):
        calibrationwidget.setObjectName("calibrationwidget")
        calibrationwidget.resize(500, 838)
        calibrationwidget.setMinimumSize(QtCore.QSize(500, 0))
        calibrationwidget.setMaximumSize(QtCore.QSize(900, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(calibrationwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.label_14 = QtWidgets.QLabel(calibrationwidget)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14, 0, QtCore.Qt.AlignHCenter)
        self.line = QtWidgets.QFrame(calibrationwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.groupBox_2 = QtWidgets.QGroupBox(calibrationwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.line_4 = QtWidgets.QFrame(self.groupBox_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_4.addWidget(self.line_4)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        self.label_22.setObjectName("label_22")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.dof_combobox = QtWidgets.QComboBox(self.groupBox_2)
        self.dof_combobox.setObjectName("dof_combobox")
        self.dof_combobox.addItem("")
        self.dof_combobox.addItem("")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dof_combobox)
        self.description = QtWidgets.QLineEdit(self.groupBox_2)
        self.description.setObjectName("description")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.description)
        self.name = QtWidgets.QLineEdit(self.groupBox_2)
        self.name.setInputMethodHints(QtCore.Qt.ImhDate)
        self.name.setObjectName("name")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name)
        self.verticalLayout_4.addLayout(self.formLayout_4)
        self.add_button = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_button.sizePolicy().hasHeightForWidth())
        self.add_button.setSizePolicy(sizePolicy)
        self.add_button.setObjectName("add_button")
        self.verticalLayout_4.addWidget(self.add_button, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.setStretch(2, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.line_3 = QtWidgets.QFrame(self.groupBox_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_3.addWidget(self.line_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.line_5 = QtWidgets.QFrame(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_5.sizePolicy().hasHeightForWidth())
        self.line_5.setSizePolicy(sizePolicy)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_3.addWidget(self.line_5)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.sensor_combobox = QtWidgets.QComboBox(self.groupBox_2)
        self.sensor_combobox.setObjectName("sensor_combobox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sensor_combobox)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        self.remove_button = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_button.sizePolicy().hasHeightForWidth())
        self.remove_button.setSizePolicy(sizePolicy)
        self.remove_button.setObjectName("remove_button")
        self.verticalLayout_3.addWidget(self.remove_button, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(calibrationwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.line_2 = QtWidgets.QFrame(calibrationwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.groupBox_3 = QtWidgets.QGroupBox(calibrationwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter)
        self.line_6 = QtWidgets.QFrame(self.groupBox_3)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_7.addWidget(self.line_6)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.cal_sensor_combobox = QtWidgets.QComboBox(self.groupBox_3)
        self.cal_sensor_combobox.setObjectName("cal_sensor_combobox")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cal_sensor_combobox)
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setObjectName("label_23")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.port_combobox = QtWidgets.QComboBox(self.groupBox_3)
        self.port_combobox.setObjectName("port_combobox")
        self.port_combobox.addItem("")
        self.port_combobox.addItem("")
        self.port_combobox.addItem("")
        self.port_combobox.addItem("")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.port_combobox)
        self.verticalLayout_7.addLayout(self.formLayout_5)
        self.start_button = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_button.sizePolicy().hasHeightForWidth())
        self.start_button.setSizePolicy(sizePolicy)
        self.start_button.setObjectName("start_button")
        self.verticalLayout_7.addWidget(self.start_button, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_7.setStretch(2, 1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.line_7 = QtWidgets.QFrame(self.groupBox_3)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_4.addWidget(self.line_7, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.line_8 = QtWidgets.QFrame(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_8.sizePolicy().hasHeightForWidth())
        self.line_8.setSizePolicy(sizePolicy)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_8.addWidget(self.line_8)
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.point_label = QtWidgets.QLabel(self.groupBox_3)
        self.point_label.setObjectName("point_label")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.point_label)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.status_label = QtWidgets.QLabel(self.groupBox_3)
        self.status_label.setObjectName("status_label")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.status_label)
        self.verticalLayout_8.addLayout(self.formLayout_6)
        self.point_capture_button = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.point_capture_button.sizePolicy().hasHeightForWidth())
        self.point_capture_button.setSizePolicy(sizePolicy)
        self.point_capture_button.setObjectName("point_capture_button")
        self.verticalLayout_8.addWidget(self.point_capture_button, 0, QtCore.Qt.AlignHCenter)
        self.calibrate_button = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrate_button.sizePolicy().hasHeightForWidth())
        self.calibrate_button.setSizePolicy(sizePolicy)
        self.calibrate_button.setObjectName("calibrate_button")
        self.verticalLayout_8.addWidget(self.calibrate_button, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_8.setStretch(2, 1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.groupBox_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(calibrationwidget)
        QtCore.QMetaObject.connectSlotsByName(calibrationwidget)

    def retranslateUi(self, calibrationwidget):
        _translate = QtCore.QCoreApplication.translate
        calibrationwidget.setWindowTitle(_translate("calibrationwidget", "Form"))
        self.label_14.setText(_translate("calibrationwidget", "Sensor Settings"))
        self.label_3.setText(_translate("calibrationwidget", "Add Sensor"))
        self.label_5.setText(_translate("calibrationwidget", "Name"))
        self.label_22.setText(_translate("calibrationwidget", "Description"))
        self.label_17.setText(_translate("calibrationwidget", "DOF"))
        self.dof_combobox.setItemText(0, _translate("calibrationwidget", "5"))
        self.dof_combobox.setItemText(1, _translate("calibrationwidget", "6"))
        self.description.setPlaceholderText(_translate("calibrationwidget", "University College Cork"))
        self.name.setPlaceholderText(_translate("calibrationwidget", "Test Sensor"))
        self.add_button.setText(_translate("calibrationwidget", "Add"))
        self.label_4.setText(_translate("calibrationwidget", "Remove Sensor"))
        self.label_16.setText(_translate("calibrationwidget", "Select Sensor:"))
        self.remove_button.setText(_translate("calibrationwidget", "Remove"))
        self.label_2.setText(_translate("calibrationwidget", "Calibration"))
        self.label_6.setText(_translate("calibrationwidget", "Setup"))
        self.label_7.setText(_translate("calibrationwidget", "Select Sensor:"))
        self.label_23.setText(_translate("calibrationwidget", "Port:"))
        self.port_combobox.setItemText(0, _translate("calibrationwidget", "1"))
        self.port_combobox.setItemText(1, _translate("calibrationwidget", "2"))
        self.port_combobox.setItemText(2, _translate("calibrationwidget", "3"))
        self.port_combobox.setItemText(3, _translate("calibrationwidget", "4"))
        self.start_button.setText(_translate("calibrationwidget", "Start"))
        self.label_8.setText(_translate("calibrationwidget", "Status"))
        self.label_11.setText(_translate("calibrationwidget", "Point:"))
        self.point_label.setText(_translate("calibrationwidget", "None"))
        self.label_13.setText(_translate("calibrationwidget", "Status:"))
        self.status_label.setText(_translate("calibrationwidget", "None"))
        self.point_capture_button.setText(_translate("calibrationwidget", "Point Capture"))
        self.calibrate_button.setText(_translate("calibrationwidget", "Calibrate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    calibrationwidget = QtWidgets.QWidget()
    ui = Ui_calibrationwidget()
    ui.setupUi(calibrationwidget)
    calibrationwidget.show()
    sys.exit(app.exec_())

