# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'igtwidget.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_igtwidget(object):
    def setupUi(self, igtwidget):
        igtwidget.setObjectName("igtwidget")
        igtwidget.resize(600, 720)
        igtwidget.setMinimumSize(QtCore.QSize(500, 0))
        igtwidget.setMaximumSize(QtCore.QSize(900, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(igtwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.label_14 = QtWidgets.QLabel(igtwidget)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14, 0, QtCore.Qt.AlignHCenter)
        self.line = QtWidgets.QFrame(igtwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.groupBox_2 = QtWidgets.QGroupBox(igtwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_28 = QtWidgets.QLabel(self.groupBox_2)
        self.label_28.setObjectName("label_28")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.status = QtWidgets.QLabel(self.groupBox_2)
        self.status.setObjectName("status")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.status)
        self.label_30 = QtWidgets.QLabel(self.groupBox_2)
        self.label_30.setObjectName("label_30")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.port = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.port.sizePolicy().hasHeightForWidth())
        self.port.setSizePolicy(sizePolicy)
        self.port.setObjectName("port")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.port)
        self.label_32 = QtWidgets.QLabel(self.groupBox_2)
        self.label_32.setObjectName("label_32")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.localhost = QtWidgets.QCheckBox(self.groupBox_2)
        self.localhost.setText("")
        self.localhost.setObjectName("localhost")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.localhost)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.x_label = QtWidgets.QLabel(self.groupBox_2)
        self.x_label.setObjectName("x_label")
        self.horizontalLayout.addWidget(self.x_label)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.y_label = QtWidgets.QLabel(self.groupBox_2)
        self.y_label.setObjectName("y_label")
        self.horizontalLayout.addWidget(self.y_label)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.z_label = QtWidgets.QLabel(self.groupBox_2)
        self.z_label.setObjectName("z_label")
        self.horizontalLayout.addWidget(self.z_label)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label)
        self.incoming_browser = QtWidgets.QTextBrowser(self.groupBox_2)
        self.incoming_browser.setObjectName("incoming_browser")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.incoming_browser)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.apply_button = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apply_button.sizePolicy().hasHeightForWidth())
        self.apply_button.setSizePolicy(sizePolicy)
        self.apply_button.setAutoFillBackground(False)
        self.apply_button.setObjectName("apply_button")
        self.verticalLayout_4.addWidget(self.apply_button, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(igtwidget)
        QtCore.QMetaObject.connectSlotsByName(igtwidget)

    def retranslateUi(self, igtwidget):
        _translate = QtCore.QCoreApplication.translate
        igtwidget.setWindowTitle(_translate("igtwidget", "Form"))
        self.label_14.setText(_translate("igtwidget", "OpenIGTLink"))
        self.label_28.setText(_translate("igtwidget", "Status:"))
        self.status.setText(_translate("igtwidget", "OFF"))
        self.label_30.setText(_translate("igtwidget", "Port:"))
        self.port.setText(_translate("igtwidget", "18944"))
        self.label_32.setText(_translate("igtwidget", "Localhost:"))
        self.label_2.setText(_translate("igtwidget", "Coordinates:"))
        self.label_8.setText(_translate("igtwidget", "x:"))
        self.x_label.setText(_translate("igtwidget", "0"))
        self.label_6.setText(_translate("igtwidget", "y:"))
        self.y_label.setText(_translate("igtwidget", "0"))
        self.label_4.setText(_translate("igtwidget", "z:"))
        self.z_label.setText(_translate("igtwidget", "0"))
        self.label.setText(_translate("igtwidget", "Incoming:"))
        self.apply_button.setText(_translate("igtwidget", "Connect"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    igtwidget = QtWidgets.QWidget()
    ui = Ui_igtwidget()
    ui.setupUi(igtwidget)
    igtwidget.show()
    sys.exit(app.exec_())

