version: 2
formats: all

build:
   image: latest

sphinx:
   configuration: docs/conf.py

submodules:
   include:
      - Python-Anser
   recursive: true

python:
   version: 3.7
   install:
      - requirements: docs/requirements.txt