# -*- mode: python -*-

block_cipher = None


a = Analysis(['app.py'],
             pathex=['C:\\Users\\Stephen Hinds\\Documents\\python-anser'],
             binaries=[],
             datas=[('./configs/*.yaml', './configs/'),
                    ('./sensors/*.yaml', './sensors/'),
                    ('./templates/*.yaml', './templates/'),
                    ('./resources/icons/*', './resources/icons/'),
                    ('./resources/cad/*', './resources/cad/'),
                    ('../../AppData/Local/Programs/Python/Python36/Lib/site-packages/scipy/extra-dll/', '.')],
             hiddenimports=['PyQt5.sip', 'scipy._lib.messagestream', 
                            'scipy.special._ufuncs_cxx',
                            'scipy.linalg.cython_blas',
                            'scipy.linalg.cython_lapack',
                            'scipy.integrate',
                            'scipy.integrate.quadrature',
                            'scipy.integrate.odepack',
                            'scipy.integrate._odepack',
                            'scipy.integrate.quadpack',
                            'scipy.integrate._quadpack',
                            'scipy.integrate._ode',
                            'scipy.integrate.vode',
                            'scipy.integrate._dop',
                            'scipy.integrate.lsoda'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='Anser',
          debug=False,
          strip=False,
          upx=True,
          console=True,
          icon='./resources/icons/anser_logo.ico')
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='app')
