name: ''
description: ''
dof:
channel: [1]
calibration:
    1: [0, 0, 0, 0, 0, 0, 0, 0]
    2: [0, 0, 0, 0, 0, 0, 0, 0]
    3: [0, 0, 0, 0, 0, 0, 0, 0]
    4: [0, 0, 0, 0, 0, 0, 0, 0]
    5: [0, 0, 0, 0, 0, 0, 0, 0]
    6: [0, 0, 0, 0, 0, 0, 0, 0]
    7: [0, 0, 0, 0, 0, 0, 0, 0]
    8: [0, 0, 0, 0, 0, 0, 0, 0]
